### ISSUE TITLE
Open Source Strategy

### ISSUE THREAD

**Issue by tisto** [kitconcept/volto-blocks#111]
# ToDo

## Open Source

* [ ] Grid-Block: https://www.npmjs.com/package/@kitconcept/volto-blocks-grid -> credits to FZJ/BXX?
* [ ] Heading-Block: https://www.npmjs.com/package/@kitconcept/volto-heading-block -> credits + image + test + final release
* [ ] Separator-Block: https://www.npmjs.com/package/@kitconcept/volto-separator-block -> credits + image + test + final release

## Low Hanging Fruits

* [ ] Button-Block: https://github.com/kitconcept/volto-blocks/tree/master/src/components/ButtonBlock
* [ ] Carousel-Block: https://github.com/kitconcept/volto-blocks/tree/master/src/components/Carousel -> showed it in keynote (FZJ)

## Mid-Complexity

* [ ] Highlight-Block: https://github.com/kitconcept/volto-blocks/tree/master/src/components/Highlight
* [ ] Text-Pill: https://github.com/kitconcept/volto-blocks/tree/master/src/components/TextPill (needs a better name)
* [ ] Parallax-Block (FZJ): https://github.com/kitconcept/fzj-internet/tree/master/src/components/Blocks/ParallaxBlock
* [ ] Accordion-Block: just customization of EEA (https://github.com/kitconcept/volto-blocks/blob/master/src/components/Accordion/schemaEnhancer.jsx)

## High-Complexity

* [ ] Slider-Block: https://github.com/kitconcept/volto-blocks/tree/master/src/components/Slider
* [ ] Highlight-Slider-Block: https://github.com/kitconcept/volto-blocks/tree/master/src/components/HighlightSlider
* [ ] Highlight-Teaser-Block (FZJ): https://github.com/kitconcept/fzj-internet/tree/master/src/components/Blocks/Highlight-Teaser-Block

## Outside of volto-blocks

* [ ] Altemetric-Block: https://github.com/kitconcept/fzj-internet/tree/master/src/components/Blocks/AltmetricBlock
* [ ] Members: https://github.com/kitconcept/fzj-internet/tree/master/src/components/Blocks/Members
* [ ] Tab Block: https://github.com/kitconcept/fzj-internet/tree/master/src/components/Blocks/TabBlock
* [ ] Teaser-Tab-Block: https://github.com/kitconcept/fzj-internet/tree/master/src/components/Blocks/Teaser-With-Links
* [ ] Teaser-Icon: https://github.com/kitconcept/fzj-internet/tree/master/src/components/Blocks/TeaserIcon (not based on grid-block) -> maybe not ready

# Shared Components

* Style wrapper (background color in text pill)

# Block Strategy

* Publish code repository
* Separate out code with the repository (move to packages directory)
* Publish package on npm
* Make original projects use the npm block
